import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import draco3d from "draco3dgltf";
import { SHIPS } from "@nebula/config";
import { buildShipGeometry } from "./ShipFactory.js";
import { MATERIAL_SLOTS } from "./materials.js";

/**
 * Production ship GLBs (generated by `pnpm --filter @nebula/game-renderer export:glb`) must exist for every
 * ship that references one, be valid Draco-compressed glTF 2.0 binaries and match the procedural bounds
 * the renderer fits them to.
 */
const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");
const PUBLIC = join(REPO, "apps/web/public");
const GLB_MAGIC = 0x46546c67; // "glTF"
const CHUNK_JSON = 0x4e4f534a;
const CHUNK_BIN = 0x004e4942;
const DRACO = "KHR_draco_mesh_compression";

interface GltfJson {
  asset: { version: string };
  extensionsUsed?: string[];
  extensionsRequired?: string[];
  meshes?: { name?: string; primitives: { attributes: Record<string, number>; extensions?: Record<string, unknown> }[] }[];
  materials?: { name?: string }[];
  nodes?: { name?: string; mesh?: number }[];
}

function publicFile(url: string): string {
  return join(PUBLIC, url.replace(/^\//, ""));
}

function parseGlb(buf: Buffer): { json: GltfJson; binLength: number } {
  expect(buf.readUInt32LE(0)).toBe(GLB_MAGIC);
  expect(buf.readUInt32LE(4)).toBe(2);
  expect(buf.readUInt32LE(8)).toBe(buf.byteLength);
  const jsonLen = buf.readUInt32LE(12);
  expect(buf.readUInt32LE(16)).toBe(CHUNK_JSON);
  const json = JSON.parse(buf.subarray(20, 20 + jsonLen).toString("utf8")) as GltfJson;
  const binAt = 20 + jsonLen;
  expect(buf.readUInt32LE(binAt + 4)).toBe(CHUNK_BIN);
  return { json, binLength: buf.readUInt32LE(binAt) };
}

const withGlb = SHIPS.filter((s) => s.visual.glb);

describe("ship GLB assets", () => {
  it("every ship references a production GLB that exists on disk", () => {
    expect(withGlb.length).toBe(SHIPS.length);
    for (const s of SHIPS) {
      expect(s.visual.glb, s.id).toBe(`/models/ships/${s.id}.glb`);
      expect(existsSync(publicFile(s.visual.glb ?? "")), `${s.id} → ${s.visual.glb}`).toBe(true);
    }
  });

  it("ships the Draco decoder locally for web + Capacitor", () => {
    for (const f of ["draco_decoder.js", "draco_decoder.wasm", "draco_wasm_wrapper.js"]) {
      expect(existsSync(join(PUBLIC, "draco", f)), f).toBe(true);
    }
  });

  it("keeps the total ship asset payload small", () => {
    const total = withGlb.reduce((n, s) => n + statSync(publicFile(s.visual.glb ?? "")).size, 0);
    expect(total).toBeLessThan(5 * 1024 * 1024);
  });

  it.each(withGlb.map((s) => [s.id, s.visual.glb ?? ""] as const))("%s is a Draco-compressed glTF 2.0 binary", (_id, url) => {
    const { json, binLength } = parseGlb(readFileSync(publicFile(url)));
    expect(json.asset.version).toBe("2.0");
    expect(binLength).toBeGreaterThan(0);
    expect(json.extensionsUsed).toContain(DRACO);
    expect(json.extensionsRequired).toContain(DRACO);
    const meshes = json.meshes ?? [];
    expect(meshes.length).toBeGreaterThan(0);
    expect(json.materials?.length ?? 0).toBeGreaterThan(0);
    for (const m of meshes) {
      for (const p of m.primitives) {
        expect(p.extensions?.[DRACO], `${m.name ?? "mesh"} primitive`).toBeDefined();
        expect(p.attributes.POSITION).toBeDefined();
        expect(p.attributes.NORMAL).toBeDefined();
        expect(p.attributes.TEXCOORD_0).toBeDefined();
      }
    }
    // Runtime re-skins meshes by material slot name.
    const names = (json.nodes ?? []).filter((n) => n.mesh !== undefined).map((n) => n.name ?? "");
    expect(names).toContain("primary");
    for (const n of names) expect(MATERIAL_SLOTS as readonly string[]).toContain(n);
  });

  describe("decoded geometry", () => {
    let io: NodeIO;
    beforeAll(async () => {
      io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({ "draco3d.decoder": await draco3d.createDecoderModule() });
    });

    it.each(withGlb.map((s) => [s.id, s] as const))("%s decodes and matches the procedural bounds", async (_id, ship) => {
      const doc = await io.read(publicFile(ship.visual.glb ?? ""));
      const min = [Infinity, Infinity, Infinity];
      const max = [-Infinity, -Infinity, -Infinity];
      let tris = 0;
      for (const mesh of doc.getRoot().listMeshes()) {
        for (const prim of mesh.listPrimitives()) {
          const pos = prim.getAttribute("POSITION");
          expect(pos).not.toBeNull();
          if (!pos) continue;
          const pMin = pos.getMinNormalized([]);
          const pMax = pos.getMaxNormalized([]);
          for (let k = 0; k < 3; k++) {
            min[k] = Math.min(min[k] ?? Infinity, pMin[k] ?? Infinity);
            max[k] = Math.max(max[k] ?? -Infinity, pMax[k] ?? -Infinity);
          }
          tris += (prim.getIndices()?.getCount() ?? pos.getCount()) / 3;
        }
      }
      expect(tris).toBeGreaterThan(100);
      const set = buildShipGeometry(ship.visual, false);
      const tol = ship.visual.length * 0.03;
      expect(Math.abs((max[2] ?? 0) - (min[2] ?? 0) - (set.bounds.max.z - set.bounds.min.z))).toBeLessThan(tol);
      expect(Math.abs((max[0] ?? 0) - (min[0] ?? 0) - (set.bounds.max.x - set.bounds.min.x))).toBeLessThan(tol);
    });
  });
});
