/**
 * pnpm economy:simulate — runs every scenario × user count × horizon through the production
 * economy policy (treasury health, emission hard cap, circuit breakers) and writes
 * docs/ECONOMY_SIMULATION.md and docs/ECONOMY_HEALTH_REPORT.md.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BASE_PARAMS, defaultEconomyConfig, runEconomySimulation, scenarioParams, withdrawalQuote, type SimulationResult } from "@nebula/economy";
import { HORIZONS, SCENARIOS, USER_COUNTS, lamports, paramsTable, pct, scenarioTable, tok, usd, users } from "./report.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const DOCS = resolve(ROOT, "docs");

const SCENARIO_NOTES: Record<string, string> = {
  LOW_PLAYER_GROWTH: "+0.2%/day new users, 0.6%/day churn.",
  BASE_GROWTH: "+1%/day new users, 0.4%/day churn, 3% daily payer conversion, $1.60 ARPPU/day.",
  HIGH_GROWTH: "+3%/day new users.",
  HIGH_SPENDING: "5% payer conversion, $2.40 ARPPU/day.",
  LOW_SPENDING: "1.2% payer conversion, $0.90 ARPPU/day.",
  HIGH_REWARD_CLAIM: "Claim rate 50%/day, rising to 70%/day at the shock day.",
  HIGH_BOT_ACTIVITY: "Bot share 10% → 25% bot wave at the shock day; 20%/day detection.",
  HIGH_WITHDRAWAL: "Withdrawal rate 10% → 35% of held rewards per day (bank run) at the shock day.",
  MARKET_CRASH: "Token price −70% at the shock day, −0.4%/day drift, spending −40%.",
  CRYPTO_VOLATILITY: "12% daily price volatility.",
  SERVER_COST_SPIKE: "Infrastructure + RPC cost ×3.5 from the shock day."
};

function run(): { all: Map<string, SimulationResult[]>; worst: SimulationResult[] } {
  const cfg = defaultEconomyConfig();
  const all = new Map<string, SimulationResult[]>();
  for (const s of SCENARIOS) {
    const rows: SimulationResult[] = [];
    for (const u of USER_COUNTS) for (const d of HORIZONS) rows.push(runEconomySimulation(s, scenarioParams(s, u, d), cfg));
    all.set(s, rows);
  }
  const worst = USER_COUNTS.map((u) => runEconomySimulation("WORST_CASE", scenarioParams("WORST_CASE", u, 180), cfg));
  return { all, worst };
}

function simulationDoc(all: Map<string, SimulationResult[]>, worst: SimulationResult[]): string {
  const cfg = defaultEconomyConfig();
  const sym = cfg.tokenomics.symbol;
  const parts: string[] = [
    "# Economy Simulation",
    "",
    `_Generated by \`pnpm economy:simulate\` (scripts/economy-simulation) on ${new Date().toISOString().slice(0, 10)}. Deterministic (seed ${BASE_PARAMS.seed})._`,
    "",
    "The simulation engine (`packages/economy/src/simulation.ts`) runs the **same policy functions as production**: `computeTreasuryHealth`, `computeEmissionRate` (hard cap) and `detectAnomalies` (circuit breakers + throttle). Monetary values are USD-equivalent; the reward asset is modelled in whole tokens with a simulated market price. Revenue is split per config: reward pool / treasury / operating / emergency reserves. Infrastructure + RPC costs are paid from operating cash first, then by selling treasury-reserve tokens — never from the reward pool.",
    "",
    "## Policy parameters (economy.json)",
    "",
    paramsTable(cfg),
    "",
    "## Base assumptions",
    "",
    "| Assumption | Value |",
    "|---|---|",
    `| DAU / registered users | ${pct(BASE_PARAMS.dauRatio)} |`,
    `| Eligible share of DAU (age, playtime, matches) | ${pct(BASE_PARAMS.eligibleShare)} |`,
    `| Reward weight per eligible DAU per day | ${BASE_PARAMS.weightPerDau} (= ${lamports(cfg.emission.rewardUnitLamports)} ${sym} at base rate) |`,
    `| Marketplace fee revenue per DAU per day | $${BASE_PARAMS.marketFeePerDau} |`,
    `| Infrastructure cost per DAU per day | $${BASE_PARAMS.infraCostPerDau} |`,
    `| RPC cost per on-chain tx | $${BASE_PARAMS.rpcCostPerTx} |`,
    `| Starting token price | $${BASE_PARAMS.tokenPrice} (devnet SOL proxy) |`,
    `| Initial treasury funding | max(10, users/2000) tokens |`,
    `| Shock day | min(30, horizon/3) |`,
    "",
    "Column notes: **Treasury (end)** = reward pool + reserves at market price + operating cash (negative = operating deficit that must be funded externally; the reward pool is ring-fenced). **Reserve Coverage** = reward-backing reserves ÷ (outstanding liability + projected 30-day emission), minimum over the run. **Inflation** = daily growth of player-held reward tokens (distribution, not minting — supply is fixed). **Breaker days** = days with at least one circuit breaker engaged.",
    ""
  ];
  for (const s of SCENARIOS) {
    parts.push(`## ${s}`, "", SCENARIO_NOTES[s] ?? "", "", scenarioTable(all.get(s) ?? [], sym), "");
  }
  parts.push("## WORST_CASE (combined, 180 days)", "", "70% claim rush + deposits −60% + price −60% + RPC/infra ×3 + bot wave (30%) + bank run (40%/day withdrawals), all at the shock day.", "", scenarioTable(worst, sym), "");
  return parts.join("\n");
}

function healthDoc(all: Map<string, SimulationResult[]>, worst: SimulationResult[]): string {
  const cfg = defaultEconomyConfig();
  const sym = cfg.tokenomics.symbol;
  const pick = (s: string, u: number, d: number) => (all.get(s) ?? []).find((r) => r.params.startUsers === u && r.params.days === d) as SimulationResult;
  const base100k = HORIZONS.map((d) => pick("BASE_GROWTH", 100_000, d));
  const base10k = HORIZONS.map((d) => pick("BASE_GROWTH", 10_000, d));
  const w1m = worst[worst.length - 1] as SimulationResult;
  const w100k = worst.find((r) => r.params.startUsers === 100_000) as SimulationResult;
  const q = withdrawalQuote(cfg.withdrawal.min, cfg);
  const dauAt = (n: number) => Math.round(n * BASE_PARAMS.dauRatio * BASE_PARAMS.eligibleShare);
  const capDaily = Number(cfg.caps.daily) / 1e9;
  const crash = pick("MARKET_CRASH", 100_000, 180);
  const bots = pick("HIGH_BOT_ACTIVITY", 100_000, 180);
  const run = pick("HIGH_WITHDRAWAL", 100_000, 180);
  const projRow = (r: SimulationResult) =>
    `| ${r.params.days} | ${usd(r.summary.revenueUsd)} | ${usd(r.summary.rewardExpenseUsd)} | ${usd(r.summary.infraCostUsd)} | ${usd(r.summary.netMarginUsd)} | ${usd(r.summary.endTreasuryUsd)} | ${r.summary.minReserveCoverage >= 99 ? "∞" : r.summary.minReserveCoverage.toFixed(2)} | ${tok(r.summary.endOutstandingLiabilityTokens, sym)} |`;
  const projHead = "| Days | Revenue | Reward Expense | Infrastructure | Net Margin | Treasury (end) | Min Coverage | Outstanding Liability |\n|---:|---:|---:|---:|---:|---:|---:|---:|";
  return [
    "# Economy Health Report",
    "",
    `_Generated by \`pnpm economy:simulate\` on ${new Date().toISOString().slice(0, 10)} from economy.json defaults and the simulation in docs/ECONOMY_SIMULATION.md. Devnet only — tokens have no monetary value._`,
    "",
    "## Current Revenue Model",
    "",
    "- **Premium currency (Gems)** bought with devnet SOL via verified on-chain deposits (`PREMIUM_REVENUE:SOL`). Gem packs and prices come from `shop.json` / `ShopProduct`.",
    `- **Marketplace / auction / trade fees** (${pct(cfg.fees.marketplace)} marketplace, ${pct(cfg.fees.auctionSale)} auction sale, ${pct(cfg.fees.auctionListing)} listing, ${pct(cfg.fees.tradeTax)} trade tax) in credits — act as sinks.`,
    `- **Withdrawal fees**: ${pct(cfg.fees.withdrawalServicePercent)} + ${lamports(cfg.fees.withdrawalFlat)} ${sym} flat + network fee → \`FEE_REVENUE\`.`,
    "- Premium/VIP/Elite, battle pass premium and cosmetics (no power sold for crypto).",
    "",
    "## Reward Model",
    "",
    `- Season reward budget = season revenue × ${pct(cfg.rewardBudgetRatio)} + reward-pool funding recorded from the **real** treasury balance. Never unlimited: no revenue and no funding ⇒ budget 0.`,
    `- Allocation: ${Object.entries(cfg.rewardAllocation).map(([k, v]) => `${k} ${pct(v)}`).join(", ")} (validated ≤ 100%).`,
    `- Emission rate = base ${pct(cfg.emission.baseRate)} × activity × season × treasury-health multiplier × controller throttle, **hard-capped at ${pct(cfg.emission.maxRewardRate)}** of the budget per day.`,
    `- Per-player caps: ${capDaily} / ${lamports(cfg.caps.weekly)} / ${lamports(cfg.caps.season)} ${sym} (day/week/season). Eligibility: ${cfg.eligibility.minAccountAgeHours}h account age, ${cfg.eligibility.minGameplayMinutes} min play, ${cfg.eligibility.minCompletedMatches} matches, risk ≤ ${cfg.eligibility.maxRiskLevel}, eligible modes only.`,
    "- Player-facing terms: Battle Rewards, Season Rewards, Tournament Rewards, Marketplace Earnings. Never APY / interest / guaranteed return / passive income / investment.",
    "",
    "## Treasury Model",
    "",
    `- Bootstrap reads the on-chain treasury balance and books only unaccounted funds, split: reward pool ${pct(cfg.rewardBudgetRatio)}, treasury reserve ${pct(cfg.treasuryReserveRatio)}, operating ${pct(cfg.operatingReserveRatio)}, emergency ${pct(cfg.emergencyReserveRatio)}.`,
    `- Health = available reserve ÷ projected 30-day liabilities: HEALTHY ≥ ${cfg.treasuryHealth.healthy}, WATCH ≥ ${cfg.treasuryHealth.watch}, WARNING ≥ ${cfg.treasuryHealth.warning}, CRITICAL below; minimum reserve ${lamports(cfg.minTreasuryReserve)} ${sym}.`,
    "- The economy controller (blockchain-service, every 5 min) snapshots supply/flows, detects anomalies and toggles circuit breakers with audit logs.",
    "",
    "## Reward Liability",
    "",
    "- Every grant creates a `RewardLiability` (OUTSTANDING → SETTLED on claim, EXPIRED/CANCELLED otherwise).",
    "- **Invariant:** a grant is clipped so outstanding liabilities never exceed the `PLAYER_REWARD_POOL` balance (which itself only holds real, recorded funds). Verified by tests and by every simulated day in every scenario.",
    `- Base growth, 100k users, 180 days: end outstanding liability ${tok(pick("BASE_GROWTH", 100_000, 180).summary.endOutstandingLiabilityTokens, sym)}.`,
    "",
    "## Maximum Theoretical Liability",
    "",
    `- Hard bound: outstanding liability ≤ reward pool balance (grant-time check), and daily new liability ≤ season budget × ${pct(cfg.emission.maxRewardRate)}.`,
    `- Cap bound (every eligible DAU maxes the daily cap): 100k users → ${dauAt(100_000).toLocaleString("en-US")} eligible DAU × ${capDaily} = ${(dauAt(100_000) * capDaily).toLocaleString("en-US")} ${sym}/day — but the emission hard cap and pool bound apply first, so actual liability is min(cap bound, budget × rate, pool).`,
    `- Per-player season maximum: ${lamports(cfg.caps.season)} ${sym}.`,
    "",
    "## Withdrawal Exposure",
    "",
    `- Only claimed rewards (player NEBX balance) can be withdrawn; min ${lamports(cfg.withdrawal.min)}, max ${lamports(cfg.withdrawal.max)}, daily ${lamports(cfg.withdrawal.dailyLimit)} ${sym} per player, ${cfg.withdrawal.cooldownMinutes} min cooldown, ${cfg.withdrawal.walletChangeLockHours}h wallet-change lock, ≥ ${lamports(cfg.withdrawal.reviewThreshold)} ${sym} → manual review.`,
    `- Minimum withdrawal quote: requested ${q.requested}, service fee ${q.serviceFee}, network fee ${q.networkFee}, final ${q.final} lamports.`,
    `- Bank-run scenario (HIGH_WITHDRAWAL, 100k, 180d): withdrawals ${usd(run.summary.withdrawalsUsd)}, breaker days ${run.summary.breakerDays}, liability exceeded pool: ${run.summary.liabilityEverExceededPool ? "YES" : "never"}.`,
    "- Funds are held in `WITHDRAWAL_RESERVE` at request time; COMPLETED only after on-chain confirmation; failures refund principal + fees.",
    "",
    "## Inflation Risk",
    "",
    `- Credits (minted soft currency): controller watches daily/weekly inflation (targets ${pct(cfg.inflation.dailyThreshold)} / ${pct(cfg.inflation.weeklyThreshold)}; spike ${pct(cfg.circuitBreaker.inflationSpike)} ⇒ EVENT_PAUSE + reward throttle ×${cfg.inflation.responses.rewardMultiplier}).`,
    `- ${sym}: fixed max supply ${cfg.tokenomics.maxSupply.toLocaleString("en-US")}, no infinite mint; rewards are distributed from a funded pool, so "inflation" is distribution of existing supply (base growth 100k/180d avg ${pct(pick("BASE_GROWTH", 100_000, 180).summary.avgInflation)} per day of player-held balance).`,
    "",
    "## Bot Risk",
    "",
    "- Heuristics: repeated reward extraction, metronome-regular intervals, account clustering by device fingerprint / IP / wallet relationships (deposits & withdrawals). Signals raise risk score → HIGH/CRITICAL ⇒ rewards PENDING_REVIEW, withdrawals to manual review. Never an automatic permanent ban.",
    `- Bot-wave scenario (HIGH_BOT_ACTIVITY, 100k, 180d): reward expense ${usd(bots.summary.rewardExpenseUsd)}, breaker days ${bots.summary.breakerDays}; circuit breaker REWARD_PAUSE engages when > ${pct(cfg.circuitBreaker.botRiskShareMax)} of rewarded users are high-risk.`,
    "",
    "## Market Risk",
    "",
    `- Rewards and liabilities are denominated in the reward asset, so a price crash does not break reserve coverage; it raises the token cost of fiat-denominated infrastructure. MARKET_CRASH (100k, 180d): treasury ${usd(crash.summary.endTreasuryUsd)}, net margin ${usd(crash.summary.netMarginUsd)}, min coverage ${crash.summary.minReserveCoverage >= 99 ? "∞" : crash.summary.minReserveCoverage.toFixed(2)}.`,
    "- MARKET_PAUSE breaker exists for marketplace manipulation (volume spike with > 50% from a single seller).",
    "",
    "## Worst Case",
    "",
    "70% claim rush + deposits −60% + price −60% + RPC/infra ×3 + 30% bot wave + 40%/day withdrawals:",
    "",
    "| Users | Revenue | Reward Expense | Infra | Treasury (end) | Min Coverage | Breaker days | Throttled/paused days | Liability > pool? |",
    "|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ...worst.map((r) => `| ${users(r.params.startUsers)} | ${usd(r.summary.revenueUsd)} | ${usd(r.summary.rewardExpenseUsd)} | ${usd(r.summary.infraCostUsd)} | ${usd(r.summary.endTreasuryUsd)} | ${r.summary.minReserveCoverage >= 99 ? "∞" : r.summary.minReserveCoverage.toFixed(2)} | ${r.summary.breakerDays} | ${r.summary.throttledDays} | ${r.summary.liabilityEverExceededPool ? "YES" : "never"} |`),
    "",
    `Result: breakers engage (${[...new Set(w1m.days.flatMap((d) => d.breakers))].join(", ") || "none"} at 1M users), emission throttles/pauses, and the reward liability never exceeds the funded pool. A negative treasury total at small scale is an **operating deficit** (infrastructure > revenue) that must be covered by external funding — it never touches the ring-fenced reward pool. At 100k users the worst case ends at ${usd(w100k.summary.endTreasuryUsd)}.`,
    "",
    "## 30 / 90 / 180 / 365-Day Projections (BASE_GROWTH)",
    "",
    "### 10k starting users",
    "",
    projHead,
    ...base10k.map(projRow),
    "",
    "### 100k starting users",
    "",
    projHead,
    ...base100k.map(projRow),
    ""
  ].join("\n");
}

const { all, worst } = run();
mkdirSync(DOCS, { recursive: true });
writeFileSync(resolve(DOCS, "ECONOMY_SIMULATION.md"), simulationDoc(all, worst));
writeFileSync(resolve(DOCS, "ECONOMY_HEALTH_REPORT.md"), healthDoc(all, worst));
const runs = [...all.values()].reduce((s, r) => s + r.length, 0) + worst.length;
const violations = [...[...all.values()].flat(), ...worst].filter((r) => r.summary.liabilityEverExceededPool || r.summary.treasuryEverNegative);
console.info(`Simulated ${runs} runs (${SCENARIOS.length} scenarios × ${USER_COUNTS.length} user counts × ${HORIZONS.length} horizons + worst case).`);
console.info(`Liability/pool invariant violations: ${violations.length}`);
console.info(`Wrote docs/ECONOMY_SIMULATION.md and docs/ECONOMY_HEALTH_REPORT.md`);
if (violations.length) process.exit(1);
