/**
 * Requirements audit runner.
 *
 * Every requirement lists concrete evidence (file + regex). The runner verifies each piece of
 * evidence against the working tree, merges recorded runtime results (runtime-results.json,
 * produced by actually running the system) and derives the status mechanically:
 *
 *  BLOCKED          requirement.blocked is set (external constraint, explained)
 *  NOT_IMPLEMENTED  no implementation evidence found
 *  PARTIAL          some implementation/integration/test evidence missing, or runtime FAIL, or marked partial
 *  IMPLEMENTED      all implementation + integration evidence present, test evidence present
 *                   (unless testExempt) and runtime not FAIL
 *
 * Output: docs/REQUIREMENTS_CHECKLIST.md and docs/audit/requirements-summary.json
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { REQUIREMENTS } from "./requirements.js";
import type { Evidence, Requirement } from "./types.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

type Status = "IMPLEMENTED" | "PARTIAL" | "NOT_IMPLEMENTED" | "BLOCKED";
type RuntimeResult = { status: "PASS" | "FAIL" | "NOT_RUN" | "BLOCKED"; evidence: string };

const fileCache = new Map<string, string | null>();
function read(file: string): string | null {
  if (!fileCache.has(file)) {
    const p = join(ROOT, file);
    fileCache.set(file, existsSync(p) ? readFileSync(p, "utf8") : null);
  }
  return fileCache.get(file) ?? null;
}

function check(ev: Evidence): boolean {
  const content = read(ev.file);
  if (content === null) return false;
  if (!ev.pattern) return true;
  return new RegExp(ev.pattern, "m").test(content);
}

function fmt(evs: Evidence[] | undefined, results: boolean[]): string {
  if (!evs || evs.length === 0) return "—";
  return evs
    .map((e, i) => `${results[i] ? "✅" : "❌"} \`${e.file}\`${e.pattern ? ` /${e.pattern.replace(/\|/g, "\\|")}/` : ""}`)
    .join("<br>");
}

function loadRuntime(): Record<string, RuntimeResult> {
  const p = join(ROOT, "docs/audit/runtime-results.json");
  return existsSync(p) ? (JSON.parse(readFileSync(p, "utf8")) as Record<string, RuntimeResult>) : {};
}

interface Row {
  req: Requirement;
  status: Status;
  impl: boolean[];
  integ: boolean[];
  test: boolean[];
  runtime: RuntimeResult | null;
  why: string[];
}

function evaluate(req: Requirement, runtime: Record<string, RuntimeResult>): Row {
  const impl = req.impl.map(check);
  const integ = (req.integration ?? []).map(check);
  const test = (req.test ?? []).map(check);
  const rt = req.runtime ? runtime[req.runtime] ?? { status: "NOT_RUN" as const, evidence: "not executed" } : null;
  const why: string[] = [];
  let status: Status;
  if (req.blocked) {
    status = "BLOCKED";
    why.push(req.blocked);
  } else if (impl.length === 0 || impl.every((x) => !x)) {
    status = "NOT_IMPLEMENTED";
    why.push("no implementation evidence found");
  } else {
    status = "IMPLEMENTED";
    if (impl.some((x) => !x)) { status = "PARTIAL"; why.push("some implementation evidence missing"); }
    if (integ.some((x) => !x)) { status = "PARTIAL"; why.push("integration evidence missing"); }
    if (!req.testExempt && (test.length === 0 || test.some((x) => !x))) { status = "PARTIAL"; why.push("NOT_TESTED"); }
    // A declared runtime check only counts once it has actually PASSed (NOT_RUN/BLOCKED/FAIL → PARTIAL).
    if (rt && rt.status !== "PASS") { status = "PARTIAL"; why.push(`runtime ${rt.status}`); }
    if (req.partial) { status = "PARTIAL"; why.push(req.partial); }
  }
  return { req, status, impl, integ, test, runtime: rt, why };
}

function main(): void {
  const runtime = loadRuntime();
  const ids = new Set<string>();
  for (const r of REQUIREMENTS) {
    if (ids.has(r.id)) throw new Error(`Duplicate requirement id ${r.id}`);
    ids.add(r.id);
  }
  const rows = REQUIREMENTS.map((r) => evaluate(r, runtime));
  const count = (s: Status) => rows.filter((r) => r.status === s).length;
  const total = rows.length;
  const summary = {
    generatedAt: new Date().toISOString(),
    total,
    implemented: count("IMPLEMENTED"),
    partial: count("PARTIAL"),
    notImplemented: count("NOT_IMPLEMENTED"),
    blocked: count("BLOCKED"),
    completionPercent: Math.round((count("IMPLEMENTED") / total) * 1000) / 10,
    byCategory: {} as Record<string, Record<Status, number>>,
  };
  for (const r of rows) {
    const c = (summary.byCategory[r.req.category] ??= { IMPLEMENTED: 0, PARTIAL: 0, NOT_IMPLEMENTED: 0, BLOCKED: 0 });
    c[r.status]++;
  }

  const lines: string[] = [];
  lines.push("# Requirements Checklist");
  lines.push("");
  lines.push(`Generated by \`pnpm audit:requirements\` (scripts/audit) at ${summary.generatedAt}. Status is derived mechanically from verified evidence (file + regex present in the tree), recorded test files and runtime results in \`docs/audit/runtime-results.json\` — not from README claims.`);
  lines.push("");
  lines.push(`**Total ${total} · Implemented ${summary.implemented} · Partial ${summary.partial} · Not implemented ${summary.notImplemented} · Blocked ${summary.blocked} · Completion ${summary.completionPercent}%** (Implemented / Total × 100)`);
  lines.push("");
  lines.push("| Category | Implemented | Partial | Not implemented | Blocked |");
  lines.push("|---|---|---|---|---|");
  for (const [cat, c] of Object.entries(summary.byCategory)) {
    lines.push(`| ${cat} | ${c.IMPLEMENTED} | ${c.PARTIAL} | ${c.NOT_IMPLEMENTED} | ${c.BLOCKED} |`);
  }
  lines.push("");
  lines.push("| ID | Category | Requirement | Expected Behavior | Status | Implementation | Integration | Test | Runtime | Notes |");
  lines.push("|---|---|---|---|---|---|---|---|---|---|");
  for (const r of rows) {
    const rt = r.runtime ? `${r.runtime.status}: ${r.runtime.evidence}` : "n/a";
    const notes = [...r.why, r.req.notes ?? ""].filter(Boolean).join("; ");
    lines.push(
      `| ${r.req.id} | ${r.req.category} | ${r.req.requirement} | ${r.req.expected} | **${r.status}** | ${fmt(r.req.impl, r.impl)} | ${fmt(r.req.integration, r.integ)} | ${fmt(r.req.test, r.test)} | ${rt.replace(/\|/g, "\\|")} | ${notes.replace(/\|/g, "\\|")} |`,
    );
  }
  mkdirSync(join(ROOT, "docs/audit"), { recursive: true });
  writeFileSync(join(ROOT, "docs/REQUIREMENTS_CHECKLIST.md"), lines.join("\n") + "\n");
  writeFileSync(join(ROOT, "docs/audit/requirements-summary.json"), JSON.stringify({ ...summary, rows: rows.map((r) => ({ id: r.req.id, category: r.req.category, requirement: r.req.requirement, status: r.status, why: r.why })) }, null, 2));
  console.info(`Requirements: ${total} | implemented ${summary.implemented} | partial ${summary.partial} | not implemented ${summary.notImplemented} | blocked ${summary.blocked} | ${summary.completionPercent}%`);
}

main();
