import { chromium } from "@playwright/test";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
page.on("console", (m) => { if (m.type() !== "debug") console.log(m.type(), m.text().slice(0, 300)); });
page.on("pageerror", (e) => console.log("pageerror:", e.message));
const u = "dbg_" + Date.now().toString(36);
await page.goto("http://localhost:5173/register");
await page.getByRole("tab", { name: "Email" }).click();
await page.locator('input[name="username"]').fill(u);
await page.locator('input[name="email"]').fill(u + "@example.test");
await page.locator('input[name="password"]').fill("Frontier-Test-2026");
await page.getByTestId("email-submit").click();
await page.waitForURL(/onboarding\/faction/);
await page.getByTestId("faction-vortex").click();
await page.getByTestId("faction-confirm").click();
await page.getByTestId("faction-pledge").click();
await page.waitForURL(/onboarding\/ship/);
await page.waitForTimeout(25000);
await page.screenshot({ path: process.argv[2], timeout: 60000 });
await browser.close();
